apiVersion: v2
name: open-webui
version: 3.4.0
appVersion: "0.3.32"

home: https://www.openwebui.com/
icon: https://raw.githubusercontent.com/open-webui/open-webui/main/static/favicon.png

description: "Open WebUI: A User-Friendly Web Interface for Chat Interactions ðŸ‘‹"
keywords:
  - llm
  - chat
  - web-ui

sources:
  - https://github.com/open-webui/helm-charts
  - https://github.com/open-webui/open-webui/pkgs/container/open-webui
  - https://github.com/otwld/ollama-helm/
  - https://hub.docker.com/r/ollama/ollama

annotations:
  licenses: MIT

dependencies:
  - name: ollama
    repository: https://otwld.github.io/ollama-helm/
    version: ">=0.24.0"
    import-values:
      - child: service
        parent: ollama.service
    condition: ollama.enabled
  - name: pipelines
    repository: https://helm.openwebui.com
    version: ">=0.0.1"
    import-values:
      - child: service
        parent: pipelines.service
    condition: pipelines.enabled
